// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocerr.proto

package protocerr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CError struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Cause                *CError  `protobuf:"bytes,3,opt,name=Cause,proto3" json:"Cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CError) Reset()         { *m = CError{} }
func (m *CError) String() string { return proto.CompactTextString(m) }
func (*CError) ProtoMessage()    {}
func (*CError) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocerr_16d75d836f8dbb55, []int{0}
}
func (m *CError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CError.Unmarshal(m, b)
}
func (m *CError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CError.Marshal(b, m, deterministic)
}
func (dst *CError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CError.Merge(dst, src)
}
func (m *CError) XXX_Size() int {
	return xxx_messageInfo_CError.Size(m)
}
func (m *CError) XXX_DiscardUnknown() {
	xxx_messageInfo_CError.DiscardUnknown(m)
}

var xxx_messageInfo_CError proto.InternalMessageInfo

func (m *CError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CError) GetCause() *CError {
	if m != nil {
		return m.Cause
	}
	return nil
}

func init() {
	proto.RegisterType((*CError)(nil), "protocerr.CError")
}

func init() { proto.RegisterFile("protocerr.proto", fileDescriptor_protocerr_16d75d836f8dbb55) }

var fileDescriptor_protocerr_16d75d836f8dbb55 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x4e, 0x2d, 0x2a, 0xd2, 0x03, 0xb3, 0x84, 0x38, 0xe1, 0x02, 0x4a, 0xe1, 0x5c, 0x6c,
	0xce, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0xb3, 0x6f, 0x71, 0xba, 0x04, 0x13,
	0x58, 0x08, 0xc4, 0x14, 0x52, 0xe7, 0x62, 0x75, 0x4e, 0x2c, 0x2d, 0x4e, 0x95, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x36, 0x12, 0xd4, 0x43, 0x98, 0x0d, 0x31, 0x27, 0x08, 0x22, 0x9f, 0xc4, 0x06, 0x96,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xde, 0x9b, 0x81, 0x61, 0x7d, 0x00, 0x00, 0x00,
}
